version: '3.9' # optional since v1.27.0

volumes:
    etcd-data:


# networks:
#   app-tier:
#     driver: bridge

services:
    # ETCD UI
    etcdkeeper:
        image: evildecay/etcdkeeper
        container_name: etcdkeeper
        environment:
            - ETCD_PEER_ADDRESS=http://etcd:2379
            # - navigate to http://localhost:8080/etcdkeeper - and put host: etcd:2379 / etcd 2380
        ports:
            - 8080:8080

    # ETCD Backend
    etcd:
        image: 'bitnami/etcd:latest'
        container_name: etcd
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ENABLE_V2=true
            - ETCD_NAME=feature_toggle_etcd
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
            - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2380
            - ETCD_INITIAL_CLUSTER=default=http://0.0.0.0:2380
            - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
        volumes:
            - etcd-data:/bitnami/etcd
        ports:
            - 2379:2379
            - 2380:2380

    # My Example-service
    example-service:
        build: .
        container_name: example-service
        depends_on:
            - etcd
            - etcd-initializer
            - elasticsearch
        environment:
            - ETCD_KEY_PREFIX=/configuration/testservice
            - ETCD_ADDR=http://etcd:2380
        restart: always
        ports:
            - 3001:3001

    jaeger:
        image: jaegertracing/all-in-one
        container_name: jaeger
        environment:
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        ports:
            - 5775:5775     # udp -
            - 6831:6831     # udp -
            - 6832:6832     # udp - agentPort
            - 5778:5778
            - 16686:16686
            - 14268:14268   # collectorEndpoint
            - 14250:14250
            - 9411:9411


