swagger: "2.0"
info:
  version: "1.0.0"
  title: 'example-service'
host: "localhost:3001"
basePath: "/api/v1"
paths:
  /listMoviesByActors:
    get:
      tags:
        - "1. Which Marvel movies did each actor play in?"
      description: "Which Marvel movies did each actor play in?"
      x-swagger-router-controller: "movieController"
      operationId: "listMoviesByActors"
      responses:
        200:
          description: "ok"
          # schema:
            # $ref: '#/definitions/listMoviesByActorsResponse'
        400:
          description: "bad result"
        500:
          description: "server error"

  /listMultipleCharactersActors:
    get:
      tags:
        - "2. Actors who played more than one Marvel character?"
      description: "Actors who played more than one Marvel character?"
      x-swagger-router-controller: "movieController"
      operationId: "listMultipleCharactersActors"
      responses:
        200:
          description: "ok"
          # schema:
            # $ref: '#/definitions/listMultipleCharactersActorsResponse'
        400:
          description: "bad result"
        500:
          description: "server error"

  /getSameRoleActors:
    get:
      tags:
        - "3. BONUS – Are there 2 different actors who played the same role?"
      description: "BONUS – Are there 2 different actors who played the same role?"
      x-swagger-router-controller: "movieController"
      operationId: "getSameRoleActors"
      responses:
        200:
          description: "ok"
          # schema:
            # $ref: '#/definitions/getSameRoleActorsResponse'
        400:
          description: "bad result"
        500:
          description: "server error"

definitions:
  listMoviesByActors:
    type: "object"
    required:
      - "yourname"
    properties:
      yourname:
        type: "string"